import smtplib, ssl
import os

def send_email(message):
    """Sends message to the target email address"""
    host = "smtp.gmail.com"
    port = 465

    username = "khui3850@gmail.com"

    # App password generated by Google under Account 2-Step Verification Settings
    # Gets user environment variable with key PASSWORD to use instead of plain text
    #password = "qchoooetuqctnzsi"
    password = os.getenv("PASSWORD")        

    target = "khui3850@gmail.com"
    context = ssl.create_default_context()

    with smtplib.SMTP_SSL(host, port, context=context) as server:
        server.login(username, password)
        server.sendmail(username, target, message)

if __name__ == "__main__":
    send_email(message="HELLO THIS IS A TEST")